@startuml
skinparam packageStyle rectangle

:Motorist: as :moto:
:Manufacturer: as :manu:
:Government: as :gove:

rectangle NotSoGassed {
  (Initialization) as (init)
  (Procurement) as (proc)
  (Charge allowance) as (char)
  (Fetch gas) as (fetc)
  (Lost or stolen) as (lost)
  (Decommissioned) as (deco)

  (proc) <-down- moto
  (fetc) <-down- moto
  (lost) <-down- moto
  (deco) <-down- moto
  (charge) <-down- moto

  manu -up-> (init)
  manu -up-> (deco)

  gove -down-> (init)
  (fetc) -up-> gove


}

@enduml
